// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBv9l-9_lVLZT1OB5lhxczNPIAPkYp2MzY',
    appId: '1:262797664827:web:4367c0a013451499a1721e',
    messagingSenderId: '262797664827',
    projectId: 'instagram1-c1ed6',
    authDomain: 'instagram1-c1ed6.firebaseapp.com',
    storageBucket: 'instagram1-c1ed6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGO6hfvqZTphwCqXIi5AhZpjOv8PUwt9s',
    appId: '1:262797664827:android:f03b41dcd9bab843a1721e',
    messagingSenderId: '262797664827',
    projectId: 'instagram1-c1ed6',
    storageBucket: 'instagram1-c1ed6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDghL3uv8qBFjo8lAnM5CZ0wETY8hjJJoA',
    appId: '1:262797664827:ios:1e8bc99adad36beca1721e',
    messagingSenderId: '262797664827',
    projectId: 'instagram1-c1ed6',
    storageBucket: 'instagram1-c1ed6.firebasestorage.app',
    iosBundleId: 'com.example.instagramFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDghL3uv8qBFjo8lAnM5CZ0wETY8hjJJoA',
    appId: '1:262797664827:ios:1e8bc99adad36beca1721e',
    messagingSenderId: '262797664827',
    projectId: 'instagram1-c1ed6',
    storageBucket: 'instagram1-c1ed6.firebasestorage.app',
    iosBundleId: 'com.example.instagramFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBv9l-9_lVLZT1OB5lhxczNPIAPkYp2MzY',
    appId: '1:262797664827:web:e2a7bb53e38f318ba1721e',
    messagingSenderId: '262797664827',
    projectId: 'instagram1-c1ed6',
    authDomain: 'instagram1-c1ed6.firebaseapp.com',
    storageBucket: 'instagram1-c1ed6.firebasestorage.app',
  );
}
